[package]
name = "experiments"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.17"
itertools = "0.10.3"
chrono = "0.4.19"
rand_chacha = "0.3.1"